import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import Sitenav from "@/components/Sitenav";
import Footer from "@/components/Footer";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen grid grid-rows-[auto_1fr_auto] bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Sitenav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
